name: vikunja_app
description: Vikunja as Flutter cross platform app

version: 0.1.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.3
  flutter_secure_storage: 4.2.0
  http: 0.13.3
  after_layout: 1.1.0
  #alice: 0.2.1
  datetime_picker_formfield: 2.0.0
  flutter_typeahead: 3.1.3
  build: 2.0.2
  json_serializable: 4.1.3
  petitparser: 4.1.0
  provider: 5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    version: any
  test: 1.16.8
  flutter_launcher_icons: 0.9.0

flutter_icons:
  image_path: "assets/vikunja_logo.png"
  image_path_ios: "assets/vikunja_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#FF455486"
  adaptive_icon_foreground: "assets/vikunja_logo_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/hypnotize.png
    - assets/vikunja_logo.png
    - assets/vikunja_logo_full.png
    - assets/vikunja_logo_full_white.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand-v7-latin-regular.ttf
