name: vikunja_app
description: Vikunja as Flutter cross platform app

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_secure_storage: 3.3.5
  http: 0.12.0+3
  after_layout: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter_icons:
  image_path: "assets/vikunja_logo.png"
  image_path_ios: "assets/vikunja_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#FF455486"
  adaptive_icon_foreground: "assets/vikunja_logo_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/hypnotize.png
    - assets/vikunja_logo.png
    - assets/vikunja_logo_full.png
    - assets/vikunja_logo_full_white.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand-v7-latin-regular.ttf
