name: vikunja_app
description: Vikunja as Flutter cross platform app

version: 0.1.8-beta

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.22.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  after_layout: ^1.2.0
  intl: ^0.20.2
  flutter_local_notifications: ^18.0.1
  rxdart: ^0.28.0
  flutter_timezone: ^4.1.0
  flutter_secure_storage: ^9.0.0
  datetime_picker_formfield: ^2.0.1
  flutter_typeahead: ^5.2.0
  build: ^2.4.1
  json_serializable: ^6.7.1
  petitparser: ^6.0.2
  provider: ^6.1.2
  webview_flutter: ^4.7.0
  flutter_colorpicker: ^1.1.0
  flutter_keyboard_visibility: ^6.0.0
  dotted_border: ^2.1.0
  url_launcher: ^6.2.5
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  permission_handler: ^11.3.0
  dynamic_color: ^1.7.0
  flutter_widget_from_html: ^0.15.2
  flutter_downloader: ^1.11.6
  meta: ^1.11.0
  timezone: ^0.10.0
  json_annotation: ^4.8.1
  collection: ^1.18.0
  cupertino_http: ^2.0.2
  cronet_http: ^1.2.0
  package_info_plus: ^8.2.1
  html_editor_enhanced: ^2.6.0
  sentry_flutter: ^8.9.0

dependency_overrides:
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview
      path: flutter_inappwebview
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
    version: any
  test: ^1.24.9
  flutter_launcher_icons: ^0.14.3

flutter_icons:
  image_path: "assets/vikunja_logo.png"
  image_path_ios: "assets/vikunja_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#FF455486"
  adaptive_icon_foreground: "assets/vikunja_logo_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/hypnotize.png
    - assets/vikunja_logo.png
    - assets/vikunja_logo_full.png
    - assets/vikunja_logo_full_white.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand-v7-latin-regular.ttf
