name: vikunja_app
description: Vikunja as Flutter cross platform app

version: 0.1.4-beta

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  http: ^0.13.5
  after_layout: ^1.2.0
  intl: ^0.17.0
  flutter_local_notifications: ^9.8.0+1
  rxdart: ^0.27.5
  flutter_timezone: ^1.0.4
  flutter_secure_storage: ^8.0.0
  datetime_picker_formfield: ^2.0.1
  flutter_typeahead: ^5.0.1
  build: ^2.3.0
  json_serializable: ^6.3.1
  petitparser: ^5.0.0
  provider: ^6.0.3
  webview_flutter: ^4.4.3
  flutter_colorpicker: ^1.0.3
  flutter_keyboard_visibility: ^5.4.2
  dotted_border: ^2.0.0+2
  package_info_plus: ^3.0.2
  url_launcher: ^6.1.7
  workmanager: ^0.5.1
  permission_handler: ^10.2.0
  dynamic_color: ^1.6.6
  chewie: ^1.5.0
  flutter_widget_from_html: ^0.14.10
  flutter_downloader: ^1.11.6


dev_dependencies:
  flutter_test:
    sdk: flutter
    version: any
  test: ^1.21.1
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  image_path: "assets/vikunja_logo.png"
  image_path_ios: "assets/vikunja_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#FF455486"
  adaptive_icon_foreground: "assets/vikunja_logo_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/hypnotize.png
    - assets/vikunja_logo.png
    - assets/vikunja_logo_full.png
    - assets/vikunja_logo_full_white.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand-v7-latin-regular.ttf
