name: vikunja_app
description: Vikunja as Flutter cross platform app

version: 0.1.8-beta

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  intl: ^0.20.2
  flutter_local_notifications: ^19.4.1
  flutter_timezone: ^4.1.0
  flutter_secure_storage: ^9.0.0
  datetime_picker_formfield_new: ^2.1.0
  flutter_typeahead: ^5.2.0
  provider: ^6.1.2
  webview_flutter: ^4.7.0
  flutter_colorpicker: ^1.1.0
  url_launcher: ^6.2.5
  workmanager: ^0.9.0
  permission_handler: ^11.3.0
  dynamic_color: ^1.7.0
  flutter_widget_from_html: ^0.17.1
  flutter_downloader: ^1.11.6
  meta: ^1.11.0
  timezone: ^0.10.0
  collection: ^1.18.0
  cupertino_http: ^2.0.2
  cronet_http: ^1.2.0
  package_info_plus: ^8.2.1
  html_editor_enhanced: ^2.6.0
  sentry_flutter: ^9.6.0
  sentry_logging: ^9.6.0
  home_widget: ^0.8.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  path_provider: ^2.1.5
  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview
      path: flutter_inappwebview
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
    version: any
  test: ^1.24.9
  flutter_launcher_icons: ^0.14.3
  riverpod_generator: ^2.6.5
  build_runner: ^2.5.4
  custom_lint: ^0.7.6
  riverpod_lint: ^2.6.5

flutter_icons:
  image_path: "assets/vikunja_logo.png"
  image_path_ios: "assets/vikunja_ios.png"
  android: true
  ios: true
  adaptive_icon_background: "#FF455486"
  adaptive_icon_foreground: "assets/vikunja_logo_adaptive.png"

flutter:
  uses-material-design: true
  assets:
    - assets/graphics/hypnotize.png
    - assets/vikunja_logo.png
    - assets/vikunja_logo_full.png
    - assets/vikunja_logo_full_white.png
  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand-v7-latin-regular.ttf
